
zlog.console.name=CONSOLE
zlog.console.enable=true
zlog.console.level=trace
zlog.console.outTypeEnum=CONSOLE
zlog.console.pattern=[%DATE_TIME]-[%LEVEL]-[%THREAD]-[%CLASS_NAME::%METHOD@%LINE_NUMBER] : [%MESSAGE]

zlog.file.name=FILE
zlog.file.enable=true
zlog.file.level=TRACE
zlog.file.outTypeEnum=FILE
zlog.file.pattern=[%DATE_TIME]-[%LEVEL]-[%THREAD]-[%CLASS_NAME::%METHOD@%LINE_NUMBER] : [%MESSAGE]
zlog.file.filePath=C:/__TEMP/
zlog.file.fileName=zrepository.log
zlog.file.fileSize=1000

zlog.logcenter.name=LOG_CENTER
zlog.logcenter.secretKey=zhang
zlog.logcenter.appId=2
zlog.logcenter.appName=zlog2
zlog.logcenter.enable=false
zlog.logcenter.logCenterUrl=http://192.168.1.6:12222/
zlog.logcenter.level=TRACE
zlog.logcenter.outTypeEnum=FILE
zlog.logcenter.pattern=[%DATE_TIME]-[%LEVEL]-[%THREAD]-[%CLASS_NAME::%METHOD@%LINE_NUMBER] : [%MESSAGE]
